### ISSUE TITLE
Minimal tiler issues

### ISSUE THREAD

**Issue by Favo02** [barnscott/newworkspaceshortcut-barnix.io#17]
Hello, first of all thanks for the useful extension!

The last update, that added new shortcuts for "Minimal tiling" broke a few things (in my experience):

- `ctrl+shift+{left/right}`: how am I supposed to highlight text (`shift+{left/right}`) while navigating words (`ctrl+{left/right}`)?
- `super+space`: isn't that the default shortcut for changing keyboard layout?

My suggestion is simply to add a **switch to completely disable** all the "Minimal tiling" shortcuts altogether _(for users that have a tiling manager like myself)_.

An even better idea is to let the user _customize the shortcuts_ in the extension preferences, but that's already a TODO and needs a bit more work.

Right now I simply deleted some lines from the source code of the extension, but I will try to find some time and implement the latter idea and submit a pull request, but I cannot guarantee anything as its a pretty busy month.

**Comment by barnscott** [comment]
Awesome, thanks for feedback!

Yea, I like that idea. I can add a toggle to disable Tiler stuff, and I can have it disabled by default. I'll try to make time to implement this.

As you mentioned, Ive been meaning to add ability to customize shortcuts, but just haven't found time for it; I had trouble with it over a year ago and just need to spend more time on it. To start with, I'd like to update the schema to allow a user to change shortcuts via `gsettings` command. (PRs welcome, as i likely wont make time for this is in short order)

**Comment by barnscott** [comment]
From my testing, it looks like i have the basic functionality working. If you want to test it from the branch, that would be great. I have submitted the changes to Gnome-Extensions too. 

After the Gnome review is complete, i will merge the change (incase they spot any issues that require attention).

**Comment by barnscott** [comment]
The update was accepted/published on Gnome-Extensions, so you can test the update there.

I'll merge the branch when I have time.

**Comment by Favo02** [comment]
Thanks for the update. I will let you know if I find any issue, closing issue
